create table "public"."attitudes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "name" character varying
);


alter table "public"."attitudes" enable row level security;

create table "public"."names" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "name" character varying
);


alter table "public"."names" enable row level security;

create table "public"."races" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "name" character varying
);


alter table "public"."races" enable row level security;

CREATE UNIQUE INDEX attitudes_pkey ON public.attitudes USING btree (id);

CREATE UNIQUE INDEX names_pkey ON public.names USING btree (id);

CREATE UNIQUE INDEX races_pkey ON public.races USING btree (id);

alter table "public"."attitudes" add constraint "attitudes_pkey" PRIMARY KEY using index "attitudes_pkey";

alter table "public"."names" add constraint "names_pkey" PRIMARY KEY using index "names_pkey";

alter table "public"."races" add constraint "races_pkey" PRIMARY KEY using index "races_pkey";

create policy "Enable read access for all users"
on "public"."attitudes"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."names"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."races"
as permissive
for select
to public
using (true);



