import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { Flex } from './styles'
import { useState } from 'react'
import { initialCards } from './initialCards'
import Card from './components/Card/Card'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [cards, setCards] = useState(initialCards);

  const initializeGame = () => {
    // Pick initialCards.length / 2 symbols from symbolPool randomly
    // Create an array that includes two of each selected symbol, then randomize them
    // Assign each card a symbol that corresponds to its index
  }

  const flipCardById = id => {
    const nextCards = cards.map(card => {
      if (card.id !== id) {
        return card;
      } else {
        card.isFlipped = true;
        return card;
      }
    })
    setCards(nextCards);
  }

  // At the proper time, determine if a match has been found. Reflip cards if not. If so, leave cards flipped. If the game is won, show success and new game button.

  return (
    <>
      <Head>
        <title>Concentration</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{ fontSize: 24 }}>Concentration</div>
        <Flex>
          {cards.map(card => (
            <Card 
              key={card.id}
              id={card.id}
              isFlipped={card.isFlipped}
              flipCardById={flipCardById} />
          ))}
        </Flex>
      </main>
    </>
  )
}
